version: '3.12'

services:
  moderator-service:
    image: toponedevopssng/moderator_service:1.0
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - llm-service

  llm-service:
    image: toponedevopssng/llm-service:1.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge