version: '3.12'

services:
  moderator-service:
    image: ghcr.io/lisa-itmo/llm-resume-moderator/app:main
    environment:
      - MLP_API_KEY=${MLP_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "8000:8000"
    networks:
      - app-network
      - elk
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  llm-service:
    image: toponedevopssng/llm-service:1.1
    networks:
      - app-network
    profiles:
      - llm-local


  elasticsearch:
    image: elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk
    
  configure-kibana-password:
    image: curlimages/curl
    networks:
      - elk
    depends_on:
      - elasticsearch
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
    command: >
      sh -c '
      until curl -X POST -u elastic:$$ELASTIC_PASSWORD
      -H "Content-Type: application/json"
      http://elasticsearch:9200/_security/user/kibana_system/_password
      -d "{\"password\":\"$$KIBANA_PASSWORD\"}" | grep -q "^{}";
      do sleep 10; done;
      echo "Password updated successfully";
      '


  kibana:
    image: kibana:8.9.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

    networks:
      - elk
    depends_on:
      - configure-kibana-password

  cache-request:
    image: curlimages/curl:latest
    networks:
      - app-network
    depends_on:
      moderator-service:
        condition: service_healthy
    environment:
      TARGET_URL: "http://moderator-service:8000/moderator/answer"
    command: >
      sh -c '
      REQUEST_BODY='\''{"rules": null, "moderation_model": null, "resume": {"experience": "1 год веб дизайн", "job_title": "веб дизайнер", "education": "Высшее", "additional_education": "нет"}}'\'';
      echo "Sending test request to $${TARGET_URL}";
      curl -X POST "$${TARGET_URL}" \
        -H "Content-Type: application/json" \
        -d "$${REQUEST_BODY}";
      echo -e "\nRequest completed with status: $$?"
      '

volumes:
  es_data:

networks:
  app-network:
    driver: bridge
  elk:
    driver: bridge
